public  class Arthimaticcalculations {
    //Test Making changes
    public void Addition(integer x,integer y){
        integer sum = x + y;
        system.debug(sum);

    }
    //Changes done in dev branch
    public void Subtraction(integer x, integer y){
        integer z = x - y;
        system.debug(z);

    }
    public void Multiplication(integer x, integer y,integer m){
        integer mult = x* y* m;
        system.debug(mult);
    }
}
