public  class Calculator {
   // class body.
   // we write everything inside class body.
// parameter: msg = message to print. Datetype is string 
public void printNewMessage(string msg){
  string msg1 = 'something'; // this is fixed string
// msg is variable name.
// used ONLY inside the metod
system.debug(msg);

}

public void add(){
    integer a =50
    integer b = 100
    integer sum = a+b;
    system.debug(sum);
}

}
