public  class checkDatatypes {
    public void MethodBoolean (){
        boolean checkBoolean;
        system.debug('Before Intializatin :' + checkBoolean);
        checkBoolean= true;
        system.debug('After Intializatin:' + checkBoolean);
    }

public void MethodInteger(){
    integer varfirst=1;
    integer varsecond=2;
    system.debug('First variabal :' + varfirst + '   '+ 'Second variable:'+ varsecond);
}

 public void Stringmethod(){
    string varname= 'Name:';
    string var2name ='Ercan';
    system.debug(varname +' ' + var2name);
}

}