public  class FirstLesson {
   public void ibnHacer(){
    string firtsName = 'Ercan';
    string lastName = 'Tas';
    string fullName = firtsName +' '+ lastName;
    system.debug('bugun benim mutlu gunum cunku dersleri anlamaya basladim allaha nekadar sukur etsem azdir');
    system.debug(fullName);
   }
   public void stringMetotlar(){

    string ssd = 'hello ercan';
    string ssd2 = ssd.capitalize();
    system.debug('capitalize metodu'+ ssd2);

   string canada = 'ercan';
   string canada2 = 'tas';
   Boolean rasult = canada.contains(canada2);
   system.debug ('contains metodu' + result);
   string ben = 'geldim';
string trimmed = ben.trim();
system.debug('trim metodu' + trimmed):
   }
}

