public  class LoopDemo {
    public void print_int_while(){
        integer count = 1;
        while (count <= 25){
            system.debug(count);
            count++;
        }
    }
    public void print_N_Odd_numbers(integer startInt ,integer endInt){
        for (Integer i = startInt;  i<= endInt; i++){
            // get remainder
            integer modI = math.mod(i 2);
            // if remainder is 1, then print.else next.
            if(modI == ){
                system.debug(i);
            }
        }

    }
        }
       
    }
}
