public class SetDemo {
   public static void citySet() {
    Set<string> cities = new set<string>();
    cities.add('Tokyo');
    cities.add('Berlin');
    cities.add('Nairobi');
    cities.add('Lisbon');
    cities.add('Tokyo');
    cities.add('Berlin');
    cities.add('Nairobi');
    cities.add('Tokyo');
     cities.add('Berlin');
    cities.add('Nairobi');

    system.debug('list of cities' + cities);
   
}
public static set<integer> setFromList(List<integer> intList) {
    set<integer> inSet = new Set<integer>();
    intSet.addAll(intList);
    return intSet;

}

}
